/* build_ammanmap.js — bakes raw OpenStreetMap data (Overpass `out geom`)
   for central Amman into a compact local module js/amman-map.js, so the
   lab runs offline via file:// with no runtime network call (same spirit
   as build.js → js/main.js).

   ── How to (re)generate the real data ──────────────────────────────
   1) Fetch from Overpass (any of the mirrors), saving as _amman_raw.json:

        curl -s -X POST https://overpass-api.de/api/interpreter \
          --data-binary @query.ql -o _amman_raw.json

      where query.ql is:
        [out:json][timeout:60];
        (
          way["highway"~"^(motorway|trunk|primary|secondary|tertiary|residential|unclassified|living_street|pedestrian|service)$"](around:520,31.9539,35.9106);
          way["building"](around:520,31.9539,35.9106);
        );
        out geom;

   2) node build_ammanmap.js          → writes js/amman-map.js

   To target a different city, change CENTER below and refetch. If Overpass
   is ever blocked/slow in your environment, drop a SYNTHETIC _amman_raw.json
   with the same `{elements:[{type:'way',tags,geometry:[{lat,lon}...]}]}`
   shape and this script will bake it the same way — the lab never cares
   whether the data is real or a stand-in.
*/
'use strict';
var fs = require('fs');

var CENTER = { lat: 31.9539, lng: 35.9106 };
var raw = JSON.parse(fs.readFileSync('./_amman_raw.json', 'utf8'));

/* GPS → local metres about CENTER (x = east, z = north-away) */
var MX = 111320 * Math.cos(CENTER.lat * Math.PI / 180);
var MZ = 110540;
function toLocal(lat, lng) {
  return [(lng - CENTER.lng) * MX, -(lat - CENTER.lat) * MZ];
}
var r1 = function (n) { return Math.round(n * 10) / 10; };

/* deterministic pseudo-random so the bake is reproducible */
function rng(seed) { var s = seed % 2147483647; if (s <= 0) s += 2147483646;
  return function () { s = (s * 16807) % 2147483647; return (s - 1) / 2147483646; }; }
var rand = rng(1337);

var RADIUS = 500;                 /* drop anything past this from centre */
function inRange(x, z) { return x * x + z * z <= RADIUS * RADIUS; }

/* ── streets ── */
var streets = [];
var minX = 1e9, maxX = -1e9, minZ = 1e9, maxZ = -1e9;
function track(x, z) { if (x < minX) minX = x; if (x > maxX) maxX = x;
  if (z < minZ) minZ = z; if (z > maxZ) maxZ = z; }

raw.elements.forEach(function (el) {
  if (el.type !== 'way' || !el.geometry || !el.tags || !el.tags.highway) return;
  var pts = [], any = false;
  el.geometry.forEach(function (g) {
    var p = toLocal(g.lat, g.lon);
    if (inRange(p[0], p[1])) any = true;
    pts.push(r1(p[0]), r1(p[1]));
  });
  if (any && pts.length >= 4) {
    for (var i = 0; i < pts.length; i += 2) track(pts[i], pts[i + 1]);
    streets.push(pts);
  }
});

/* ── buildings → axis-aligned grey boxes ── */
var buildings = [];
raw.elements.forEach(function (el) {
  if (el.type !== 'way' || !el.geometry || !el.tags || !el.tags.building) return;
  var bx0 = 1e9, bx1 = -1e9, bz0 = 1e9, bz1 = -1e9, inside = false;
  el.geometry.forEach(function (g) {
    var p = toLocal(g.lat, g.lon);
    if (inRange(p[0], p[1])) inside = true;
    if (p[0] < bx0) bx0 = p[0]; if (p[0] > bx1) bx1 = p[0];
    if (p[1] < bz0) bz0 = p[1]; if (p[1] > bz1) bz1 = p[1];
  });
  if (!inside) return;
  var w = bx1 - bx0, d = bz1 - bz0;
  if (w < 3 || d < 3 || w > 160 || d > 160) return;   /* skip slivers / mega-polys */
  /* height: prefer real tags, else random 10–40 m (per spec) */
  var h = 0, t = el.tags;
  if (t.height) h = parseFloat(t.height);
  else if (t['building:levels']) h = parseFloat(t['building:levels']) * 3.2;
  if (!(h > 0)) h = 10 + rand() * 30;
  h = Math.max(8, Math.min(46, h));
  buildings.push([r1((bx0 + bx1) / 2), r1((bz0 + bz1) / 2), r1(w), r1(d), r1(h)]);
});

var out = {
  center: CENTER,
  bounds: { minX: r1(minX), maxX: r1(maxX), minZ: r1(minZ), maxZ: r1(maxZ) },
  streets: streets,
  buildings: buildings
};

var js = '/* amman-map.js — AUTO-GENERATED by build_ammanmap.js. Do not edit by hand.\n' +
  '   Central Amman (' + CENTER.lat + ', ' + CENTER.lng + '), ~' + RADIUS + ' m radius,\n' +
  '   from OpenStreetMap via Overpass. Coords are local metres (x=east, z=north-away).\n' +
  '   © OpenStreetMap contributors (ODbL). */\n' +
  'var AMMAN_MAP = ' + JSON.stringify(out) + ';\n';
fs.writeFileSync('js/amman-map.js', js);

console.log('streets:', streets.length, ' buildings:', buildings.length);
console.log('bounds:', out.bounds);
console.log('wrote js/amman-map.js (' + (js.length / 1024).toFixed(1) + ' KB)');
